/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as MerchantRouteImport } from './routes/merchant'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppAchievementsRouteImport } from './routes/app.achievements'
import { Route as AppActivityRouteImport } from './routes/app.activity'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as AppAlliancesRouteImport } from './routes/app.alliances'
import { Route as AppAnalyticsRouteImport } from './routes/app.analytics'
import { Route as AppConsoleRouteImport } from './routes/app.console'
import { Route as AppDiscoverRouteImport } from './routes/app.discover'
import { Route as AppIssuerRouteImport } from './routes/app.issuer'
import { Route as AppRewardsRouteImport } from './routes/app.rewards'
import { Route as AppSwapRouteImport } from './routes/app.swap'
import { Route as AppVerifyRouteImport } from './routes/app.verify'
import { Route as AppWalletRouteImport } from './routes/app.wallet'
import { Route as AppConsoleTabRouteImport } from './routes/app.console_.$tab'
import { Route as AppMerchantAddressRouteImport } from './routes/app.merchant.$address'
import { Route as AppTokenMintRouteImport } from './routes/app.token.$mint'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantRoute = MerchantRouteImport.update({
  id: '/merchant',
  path: '/merchant',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAchievementsRoute = AppAchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => AppRoute,
} as any)
const AppActivityRoute = AppActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppAlliancesRoute = AppAlliancesRouteImport.update({
  id: '/alliances',
  path: '/alliances',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppConsoleRoute = AppConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => AppRoute,
} as any)
const AppDiscoverRoute = AppDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => AppRoute,
} as any)
const AppIssuerRoute = AppIssuerRouteImport.update({
  id: '/issuer',
  path: '/issuer',
  getParentRoute: () => AppRoute,
} as any)
const AppRewardsRoute = AppRewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => AppRoute,
} as any)
const AppSwapRoute = AppSwapRouteImport.update({
  id: '/swap',
  path: '/swap',
  getParentRoute: () => AppRoute,
} as any)
const AppVerifyRoute = AppVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => AppRoute,
} as any)
const AppWalletRoute = AppWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AppRoute,
} as any)
const AppConsoleTabRoute = AppConsoleTabRouteImport.update({
  id: '/console_/$tab',
  path: '/console/$tab',
  getParentRoute: () => AppRoute,
} as any)
const AppMerchantAddressRoute = AppMerchantAddressRouteImport.update({
  id: '/merchant/$address',
  path: '/merchant/$address',
  getParentRoute: () => AppRoute,
} as any)
const AppTokenMintRoute = AppTokenMintRouteImport.update({
  id: '/token/$mint',
  path: '/token/$mint',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/merchant': typeof MerchantRoute
  '/app/achievements': typeof AppAchievementsRoute
  '/app/activity': typeof AppActivityRoute
  '/app/admin': typeof AppAdminRoute
  '/app/alliances': typeof AppAlliancesRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/console': typeof AppConsoleRoute
  '/app/discover': typeof AppDiscoverRoute
  '/app/issuer': typeof AppIssuerRoute
  '/app/rewards': typeof AppRewardsRoute
  '/app/swap': typeof AppSwapRoute
  '/app/verify': typeof AppVerifyRoute
  '/app/wallet': typeof AppWalletRoute
  '/app/': typeof AppIndexRoute
  '/app/console/$tab': typeof AppConsoleTabRoute
  '/app/merchant/$address': typeof AppMerchantAddressRoute
  '/app/token/$mint': typeof AppTokenMintRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/merchant': typeof MerchantRoute
  '/app/achievements': typeof AppAchievementsRoute
  '/app/activity': typeof AppActivityRoute
  '/app/admin': typeof AppAdminRoute
  '/app/alliances': typeof AppAlliancesRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/console': typeof AppConsoleRoute
  '/app/discover': typeof AppDiscoverRoute
  '/app/issuer': typeof AppIssuerRoute
  '/app/rewards': typeof AppRewardsRoute
  '/app/swap': typeof AppSwapRoute
  '/app/verify': typeof AppVerifyRoute
  '/app/wallet': typeof AppWalletRoute
  '/app': typeof AppIndexRoute
  '/app/console/$tab': typeof AppConsoleTabRoute
  '/app/merchant/$address': typeof AppMerchantAddressRoute
  '/app/token/$mint': typeof AppTokenMintRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/merchant': typeof MerchantRoute
  '/app/achievements': typeof AppAchievementsRoute
  '/app/activity': typeof AppActivityRoute
  '/app/admin': typeof AppAdminRoute
  '/app/alliances': typeof AppAlliancesRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/console': typeof AppConsoleRoute
  '/app/discover': typeof AppDiscoverRoute
  '/app/issuer': typeof AppIssuerRoute
  '/app/rewards': typeof AppRewardsRoute
  '/app/swap': typeof AppSwapRoute
  '/app/verify': typeof AppVerifyRoute
  '/app/wallet': typeof AppWalletRoute
  '/app/': typeof AppIndexRoute
  '/app/console_/$tab': typeof AppConsoleTabRoute
  '/app/merchant/$address': typeof AppMerchantAddressRoute
  '/app/token/$mint': typeof AppTokenMintRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/merchant'
    | '/app/achievements'
    | '/app/activity'
    | '/app/admin'
    | '/app/alliances'
    | '/app/analytics'
    | '/app/console'
    | '/app/discover'
    | '/app/issuer'
    | '/app/rewards'
    | '/app/swap'
    | '/app/verify'
    | '/app/wallet'
    | '/app/'
    | '/app/console/$tab'
    | '/app/merchant/$address'
    | '/app/token/$mint'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/merchant'
    | '/app/achievements'
    | '/app/activity'
    | '/app/admin'
    | '/app/alliances'
    | '/app/analytics'
    | '/app/console'
    | '/app/discover'
    | '/app/issuer'
    | '/app/rewards'
    | '/app/swap'
    | '/app/verify'
    | '/app/wallet'
    | '/app'
    | '/app/console/$tab'
    | '/app/merchant/$address'
    | '/app/token/$mint'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/merchant'
    | '/app/achievements'
    | '/app/activity'
    | '/app/admin'
    | '/app/alliances'
    | '/app/analytics'
    | '/app/console'
    | '/app/discover'
    | '/app/issuer'
    | '/app/rewards'
    | '/app/swap'
    | '/app/verify'
    | '/app/wallet'
    | '/app/'
    | '/app/console_/$tab'
    | '/app/merchant/$address'
    | '/app/token/$mint'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  MerchantRoute: typeof MerchantRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant': {
      id: '/merchant'
      path: '/merchant'
      fullPath: '/merchant'
      preLoaderRoute: typeof MerchantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/achievements': {
      id: '/app/achievements'
      path: '/achievements'
      fullPath: '/app/achievements'
      preLoaderRoute: typeof AppAchievementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/activity': {
      id: '/app/activity'
      path: '/activity'
      fullPath: '/app/activity'
      preLoaderRoute: typeof AppActivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/alliances': {
      id: '/app/alliances'
      path: '/alliances'
      fullPath: '/app/alliances'
      preLoaderRoute: typeof AppAlliancesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/console': {
      id: '/app/console'
      path: '/console'
      fullPath: '/app/console'
      preLoaderRoute: typeof AppConsoleRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/discover': {
      id: '/app/discover'
      path: '/discover'
      fullPath: '/app/discover'
      preLoaderRoute: typeof AppDiscoverRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/issuer': {
      id: '/app/issuer'
      path: '/issuer'
      fullPath: '/app/issuer'
      preLoaderRoute: typeof AppIssuerRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/rewards': {
      id: '/app/rewards'
      path: '/rewards'
      fullPath: '/app/rewards'
      preLoaderRoute: typeof AppRewardsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/swap': {
      id: '/app/swap'
      path: '/swap'
      fullPath: '/app/swap'
      preLoaderRoute: typeof AppSwapRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/verify': {
      id: '/app/verify'
      path: '/verify'
      fullPath: '/app/verify'
      preLoaderRoute: typeof AppVerifyRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/wallet': {
      id: '/app/wallet'
      path: '/wallet'
      fullPath: '/app/wallet'
      preLoaderRoute: typeof AppWalletRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/console_/$tab': {
      id: '/app/console_/$tab'
      path: '/console/$tab'
      fullPath: '/app/console/$tab'
      preLoaderRoute: typeof AppConsoleTabRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/merchant/$address': {
      id: '/app/merchant/$address'
      path: '/merchant/$address'
      fullPath: '/app/merchant/$address'
      preLoaderRoute: typeof AppMerchantAddressRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/token/$mint': {
      id: '/app/token/$mint'
      path: '/token/$mint'
      fullPath: '/app/token/$mint'
      preLoaderRoute: typeof AppTokenMintRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAchievementsRoute: typeof AppAchievementsRoute
  AppActivityRoute: typeof AppActivityRoute
  AppAdminRoute: typeof AppAdminRoute
  AppAlliancesRoute: typeof AppAlliancesRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppConsoleRoute: typeof AppConsoleRoute
  AppDiscoverRoute: typeof AppDiscoverRoute
  AppIssuerRoute: typeof AppIssuerRoute
  AppRewardsRoute: typeof AppRewardsRoute
  AppSwapRoute: typeof AppSwapRoute
  AppVerifyRoute: typeof AppVerifyRoute
  AppWalletRoute: typeof AppWalletRoute
  AppIndexRoute: typeof AppIndexRoute
  AppConsoleTabRoute: typeof AppConsoleTabRoute
  AppMerchantAddressRoute: typeof AppMerchantAddressRoute
  AppTokenMintRoute: typeof AppTokenMintRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAchievementsRoute: AppAchievementsRoute,
  AppActivityRoute: AppActivityRoute,
  AppAdminRoute: AppAdminRoute,
  AppAlliancesRoute: AppAlliancesRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppConsoleRoute: AppConsoleRoute,
  AppDiscoverRoute: AppDiscoverRoute,
  AppIssuerRoute: AppIssuerRoute,
  AppRewardsRoute: AppRewardsRoute,
  AppSwapRoute: AppSwapRoute,
  AppVerifyRoute: AppVerifyRoute,
  AppWalletRoute: AppWalletRoute,
  AppIndexRoute: AppIndexRoute,
  AppConsoleTabRoute: AppConsoleTabRoute,
  AppMerchantAddressRoute: AppMerchantAddressRoute,
  AppTokenMintRoute: AppTokenMintRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  MerchantRoute: MerchantRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
